###
GET http://localhost:8080/contacts

###
GET http://localhost:8080/contacts/63ba2c1898a0c4386448e05f

###
GET https://cse341render.onrender.com/contacts

###
GET https://cse341render.onrender.com/contacts/63ba2c1898a0c4386448e05f
