### LOCAL BOOK REQUESTS
GET http://localhost:8080/book_inventory

###
GET http://localhost:8080/book_inventory/63df3f76c887912aec7a23fa

###
POST http://localhost:8080/book_inventory
content-type: application/json

{   
    "title": "Dune",
    "author": "Frank Herbert",
    "pages": "412",
    "genre": "Science Fiction",
    "publishYear": "1965",
    "invCount": "6"
}

###
PUT http://localhost:8080/book_inventory/63df42955198d6eb205e267b
content-type: application/json

{   
    "title": "Dune",
    "author": "Frank Herbert",
    "pages": "412",
    "genre": "Science Fiction",
    "publishYear": "1965",
    "invCount": "2"
}

### 
DELETE http://localhost:8080/book_inventory/63df41dc5198d6eb205e267a







### RENDER BOOK REQUESTS
GET https://cse341render.onrender.com/book_inventory

###
GET https://cse341render.onrender.com/book_inventory/63df42955198d6eb205e267b


###
POST https://cse341render.onrender.com/book_inventory
content-type: application/json

 {
   "title": "Dune",
    "author": "Frank Herbert",
    "pages": "412",
    "genre": "Science Fiction",
    "publishYear": "1965",
    "invCount": "6"
  }

###
PUT https://cse341render.onrender.com/book_inventory/63df42955198d6eb205e267b

content-type: application/json

 {
   "title": "Dune",
    "author": "Frank Herbert",
    "pages": "412",
    "genre": "Science Fiction",
    "publishYear": "1965",
    "invCount": "0"
  }

###
DELETE https://cse341render.onrender.com/book_inventory/63df42955198d6eb205e267b


